<?php
define('SG_BACKUP_GUARD_VERSION', '1.0.6');

define('SG_FEATURE_DOWNLOAD_FROM_CLOUD', 0);
define('SG_FEATURE_STORAGE', 0);
define('SG_FEATURE_FTP', 0);
define('SG_FEATURE_AMAZON', 0);
define('SG_FEATURE_DROPBOX', 0);
define('SG_FEATURE_GOOGLE_DRIVE', 0);
define('SG_FEATURE_SCHEDULE', 0);
define('SG_FEATURE_DELETE_LOCAL_BACKUP_AFTER_UPLOAD', 0);
define('SG_FEATURE_NUMBER_OF_BACKUPS_TO_KEEP', 0);
define('SG_FEATURE_CUSTOM_BACKUP_NAME', 0);
define('SG_FEATURE_SUBDIRECTORIES', 0);
define('SG_FEATURE_BACKGROUND_MODE', 0);
define('SG_FEATURE_NOTIFICATIONS', 0);
define('SG_FEATURE_MULTI_SCHEDULE', 0);

define('SG_FEATURE_SHOW_UPGRADE_PAGE', 1);
