<?php
	$url = $_SERVER['REQUEST_URI'];
	function sgBuildUrl($action) {
		return Mage::helper("adminhtml")->getUrl("adminhtml/backupguardfree/".$action);
	}
?>
<div id="sg-sidebar-wrapper" class="metro">
	<nav class="sidebar dark">
		<ul>
			<li class="title"><a class="sg-site-url" target="_blank" href="<?php echo SG_BACKUP_SITE_URL;?>"></a></li>
				<li class="<?php echo strpos($url,'backups')?'active':''?>">
					<a href="<?php echo sgBuildUrl('backups'); ?>">
						<span class="glyphicon glyphicon-hdd"></span>
						Backups
					</a>
				</li>
				<li class="<?php echo strpos($url,'settings')?'active':''?>">
					<a href="<?php echo sgBuildUrl('settings'); ?>">
						<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
						Settings
					</a>
				</li>
			<li class="<?php echo strpos($url,'support')?'active':''?>">
				<a href="<?php echo sgBuildUrl('support'); ?>">
					<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
					Support
				</a>
			</li>
			<li class="<?php echo strpos($url,'whyupgrade')?'active':''?>">
				<a href="<?php echo sgBuildUrl('whyupgrade'); ?>">
					<span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
					Why upgrade?
				</a>
			</li>
		</ul>
	</nav>

	<div class="sg-alert-pro">
		<p>Backup to cloud, automatization, mail notifications, and more in our PRO package! </p>
		<p><a class="btn btn-primary" target="_blank" href="<?php echo SG_BACKUP_GUARD_PRO_URL; ?>">Buy now!</a></p>
	</div>
</div>
