<?php
    $url = $_SERVER['REQUEST_URI'];
    function sgBuildUrl($action) {
        return Mage::helper("adminhtml")->getUrl("adminhtml/backupguardfree/".$action);
    }
?>
<div id="sg-sidebar-wrapper" class="metro">
    <nav class="sidebar dark">
        <ul>
            <li class="title"><a class="sg-site-url" target="_blank" href="<?php echo SG_BACKUP_SITE_URL;?>"></a></li>
            <li class="<?php echo strpos($url,'backups')?'active':''?>"><a href="<?php echo sgBuildUrl('backups'); ?>"><span class="glyphicon glyphicon-hdd"></span>Backups</a></li>
            <?php if(SGBoot::isFeatureAvailable('STORAGE')): ?>
                <li class="<?php echo strpos($url,'cloud')?'active':''?>"><a href="<?php echo sgBuildUrl('cloud'); ?>"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span>Cloud</a></li>
            <?php endif; ?>
            <?php if(SGBoot::isFeatureAvailable('SCHEDULE')): ?>
                <li class="<?php echo strpos($url,'schedule')?'active':''?>"><a href="<?php echo sgBuildUrl('schedule'); ?>"><span class="glyphicon glyphicon-time" aria-hidden="true"></span>Schedule</a></li>
            <?php endif; ?>
            <?php if(SGBoot::isFeatureAvailable('NOTIFICATIONS')): ?>
                <li class="<?php echo strpos($url,'settings')?'active':''?>"><a href="<?php echo sgBuildUrl('settings'); ?>"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>Settings</a></li>
            <?php endif; ?>
        </ul>
    </nav>
    <?php if(!SGBoot::isFeatureAvailable('SCHEDULE')): ?>
    <div class="sg-alert-pro">
        <p>Backup to cloud, automatization, mail notifications, and more in our PRO package! </p>
        <p><a class="btn btn-primary" target="_blank" href="<?php echo SG_BACKUP_GUARD_PRO_URL; ?>">Buy now!</a></p>
    </div>
    <?php endif; ?>
</div>